"""Multiclass level-set acquisitions with nominal duplicate semantics."""

from bochan.acquisition._nominal_duplicate_penalties import NominalDuplicatePenaltyMixin

from .hetero_multi_output import (
    qHeteroMultiOutputMulticlassBoundaryVarianceAcquisition as _qHeteroMultiOutputMulticlassBoundaryVarianceAcquisition,
    qHeteroMultiOutputMulticlassClassEntropyAcquisition as _qHeteroMultiOutputMulticlassClassEntropyAcquisition,
    qHeteroMultiOutputMulticlassICUAcquisition as _qHeteroMultiOutputMulticlassICUAcquisition,
    qHeteroMultiOutputMulticlassJointLatentStraddleAcquisition as _qHeteroMultiOutputMulticlassJointLatentStraddleAcquisition,
    qHeteroMultiOutputMulticlassLatentStraddleAcquisition as _qHeteroMultiOutputMulticlassLatentStraddleAcquisition,
    qHeteroMultiOutputMulticlassLevelSetUncertainty as _qHeteroMultiOutputMulticlassLevelSetUncertainty,
    qHeteroMultiOutputMulticlassProbabilityOfExceedance as _qHeteroMultiOutputMulticlassProbabilityOfExceedance,
)
from .hetero_single_output import (
    qHeteroMulticlassBoundaryVarianceAcquisition as _qHeteroMulticlassBoundaryVarianceAcquisition,
    qHeteroMulticlassClassEntropyAcquisition as _qHeteroMulticlassClassEntropyAcquisition,
    qHeteroMulticlassICUAcquisition as _qHeteroMulticlassICUAcquisition,
    qHeteroMulticlassJointLatentStraddleAcquisition as _qHeteroMulticlassJointLatentStraddleAcquisition,
    qHeteroMulticlassLatentStraddleAcquisition as _qHeteroMulticlassLatentStraddleAcquisition,
    qHeteroMulticlassLevelSetUncertainty as _qHeteroMulticlassLevelSetUncertainty,
    qHeteroMulticlassProbabilityOfExceedance as _qHeteroMulticlassProbabilityOfExceedance,
)
from .multi_output import (
    qMultiOutputMulticlassBoundaryVarianceAcquisition as _qMultiOutputMulticlassBoundaryVarianceAcquisition,
    qMultiOutputMulticlassClassEntropyAcquisition as _qMultiOutputMulticlassClassEntropyAcquisition,
    qMultiOutputMulticlassICUAcquisition as _qMultiOutputMulticlassICUAcquisition,
    qMultiOutputMulticlassJointLatentStraddleAcquisition as _qMultiOutputMulticlassJointLatentStraddleAcquisition,
    qMultiOutputMulticlassLatentStraddleAcquisition as _qMultiOutputMulticlassLatentStraddleAcquisition,
    qMultiOutputMulticlassLevelSetUncertainty as _qMultiOutputMulticlassLevelSetUncertainty,
    qMultiOutputMulticlassProbabilityOfExceedance as _qMultiOutputMulticlassProbabilityOfExceedance,
)
from .single_output import (
    qMulticlassBoundaryVarianceAcquisition as _qMulticlassBoundaryVarianceAcquisition,
    qMulticlassClassEntropyAcquisition as _qMulticlassClassEntropyAcquisition,
    qMulticlassICUAcquisition as _qMulticlassICUAcquisition,
    qMulticlassJointLatentStraddleAcquisition as _qMulticlassJointLatentStraddleAcquisition,
    qMulticlassLatentStraddleAcquisition as _qMulticlassLatentStraddleAcquisition,
    qMulticlassLevelSetUncertainty as _qMulticlassLevelSetUncertainty,
    qMulticlassProbabilityOfExceedance as _qMulticlassProbabilityOfExceedance,
)


def _safe(name: str, base: type) -> type:
    return type(name, (NominalDuplicatePenaltyMixin, base), {"__module__": __name__})


qMulticlassLatentStraddleAcquisition = _safe("qMulticlassLatentStraddleAcquisition", _qMulticlassLatentStraddleAcquisition)
qMulticlassJointLatentStraddleAcquisition = _safe("qMulticlassJointLatentStraddleAcquisition", _qMulticlassJointLatentStraddleAcquisition)
qMulticlassICUAcquisition = _safe("qMulticlassICUAcquisition", _qMulticlassICUAcquisition)
qMulticlassBoundaryVarianceAcquisition = _safe("qMulticlassBoundaryVarianceAcquisition", _qMulticlassBoundaryVarianceAcquisition)
qMulticlassClassEntropyAcquisition = _safe("qMulticlassClassEntropyAcquisition", _qMulticlassClassEntropyAcquisition)
qMulticlassProbabilityOfExceedance = _safe("qMulticlassProbabilityOfExceedance", _qMulticlassProbabilityOfExceedance)
qMulticlassLevelSetUncertainty = _safe("qMulticlassLevelSetUncertainty", _qMulticlassLevelSetUncertainty)

qMultiOutputMulticlassLatentStraddleAcquisition = _safe("qMultiOutputMulticlassLatentStraddleAcquisition", _qMultiOutputMulticlassLatentStraddleAcquisition)
qMultiOutputMulticlassJointLatentStraddleAcquisition = _safe("qMultiOutputMulticlassJointLatentStraddleAcquisition", _qMultiOutputMulticlassJointLatentStraddleAcquisition)
qMultiOutputMulticlassICUAcquisition = _safe("qMultiOutputMulticlassICUAcquisition", _qMultiOutputMulticlassICUAcquisition)
qMultiOutputMulticlassBoundaryVarianceAcquisition = _safe("qMultiOutputMulticlassBoundaryVarianceAcquisition", _qMultiOutputMulticlassBoundaryVarianceAcquisition)
qMultiOutputMulticlassClassEntropyAcquisition = _safe("qMultiOutputMulticlassClassEntropyAcquisition", _qMultiOutputMulticlassClassEntropyAcquisition)
qMultiOutputMulticlassProbabilityOfExceedance = _safe("qMultiOutputMulticlassProbabilityOfExceedance", _qMultiOutputMulticlassProbabilityOfExceedance)
qMultiOutputMulticlassLevelSetUncertainty = _safe("qMultiOutputMulticlassLevelSetUncertainty", _qMultiOutputMulticlassLevelSetUncertainty)

qHeteroMulticlassLatentStraddleAcquisition = _safe("qHeteroMulticlassLatentStraddleAcquisition", _qHeteroMulticlassLatentStraddleAcquisition)
qHeteroMulticlassJointLatentStraddleAcquisition = _safe("qHeteroMulticlassJointLatentStraddleAcquisition", _qHeteroMulticlassJointLatentStraddleAcquisition)
qHeteroMulticlassICUAcquisition = _safe("qHeteroMulticlassICUAcquisition", _qHeteroMulticlassICUAcquisition)
qHeteroMulticlassBoundaryVarianceAcquisition = _safe("qHeteroMulticlassBoundaryVarianceAcquisition", _qHeteroMulticlassBoundaryVarianceAcquisition)
qHeteroMulticlassClassEntropyAcquisition = _safe("qHeteroMulticlassClassEntropyAcquisition", _qHeteroMulticlassClassEntropyAcquisition)
qHeteroMulticlassProbabilityOfExceedance = _safe("qHeteroMulticlassProbabilityOfExceedance", _qHeteroMulticlassProbabilityOfExceedance)
qHeteroMulticlassLevelSetUncertainty = _safe("qHeteroMulticlassLevelSetUncertainty", _qHeteroMulticlassLevelSetUncertainty)

qHeteroMultiOutputMulticlassLatentStraddleAcquisition = _safe("qHeteroMultiOutputMulticlassLatentStraddleAcquisition", _qHeteroMultiOutputMulticlassLatentStraddleAcquisition)
qHeteroMultiOutputMulticlassJointLatentStraddleAcquisition = _safe("qHeteroMultiOutputMulticlassJointLatentStraddleAcquisition", _qHeteroMultiOutputMulticlassJointLatentStraddleAcquisition)
qHeteroMultiOutputMulticlassICUAcquisition = _safe("qHeteroMultiOutputMulticlassICUAcquisition", _qHeteroMultiOutputMulticlassICUAcquisition)
qHeteroMultiOutputMulticlassBoundaryVarianceAcquisition = _safe("qHeteroMultiOutputMulticlassBoundaryVarianceAcquisition", _qHeteroMultiOutputMulticlassBoundaryVarianceAcquisition)
qHeteroMultiOutputMulticlassClassEntropyAcquisition = _safe("qHeteroMultiOutputMulticlassClassEntropyAcquisition", _qHeteroMultiOutputMulticlassClassEntropyAcquisition)
qHeteroMultiOutputMulticlassProbabilityOfExceedance = _safe("qHeteroMultiOutputMulticlassProbabilityOfExceedance", _qHeteroMultiOutputMulticlassProbabilityOfExceedance)
qHeteroMultiOutputMulticlassLevelSetUncertainty = _safe("qHeteroMultiOutputMulticlassLevelSetUncertainty", _qHeteroMultiOutputMulticlassLevelSetUncertainty)


__all__ = [name for name in globals() if name.startswith("q")]
