from .base import (
    BlockDesignMulticlassLikelihood,
    KroneckerMultiTaskMulticlassClassificationGPModel,
    KroneckerMultiTaskMulticlassClassificationMixedGPModel,
    KroneckerMultiTaskMulticlassProbsPosterior,
    MultiOutputMulticlassClassificationGPModel,
    MultiOutputMulticlassClassificationModel,
    MultiOutputMulticlassModel,
    MultiOutputMulticlassProbsPosterior,
    MultiTaskMulticlassClassificationGPModel,
    MultiTaskMulticlassClassificationMixedGPModel,
    MulticlassClassificationGPModel,
    MulticlassClassificationMixedGPModel,
    build_mixed_multiclass_kernel,
)
from .base.models import _BaseMulticlassClassificationModel
from .deep import (
    DeepKernelMulticlassClassificationGPModel,
    DeepKernelMulticlassClassificationMixedGPModel,
    DeepMulticlassClassificationGPModel,
    DeepMulticlassClassificationMixedGPModel,
)
from .high_dim import (
    PCAMulticlassClassificationGPModel,
    PCAMulticlassClassificationMixedGPModel,
    REMBOMulticlassClassificationGPModel,
    REMBOMulticlassClassificationMixedGPModel,
    SaasMulticlassClassificationGPModel,
    SaasMulticlassClassificationMixedGPModel,
)
from .robust import (
    HeteroscedasticMulticlassClassificationGPModel,
    HeteroscedasticMulticlassClassificationMixedGPModel,
    HeteroscedasticMulticlassPosterior,
    RobustRelevancePursuitMulticlassClassificationGPModel,
    RobustRelevancePursuitMulticlassClassificationMixedGPModel,
    SparseOutlierSoftmaxLikelihood,
)

__all__ = [
    "_BaseMulticlassClassificationModel",
    "BlockDesignMulticlassLikelihood",
    "KroneckerMultiTaskMulticlassClassificationGPModel",
    "KroneckerMultiTaskMulticlassClassificationMixedGPModel",
    "KroneckerMultiTaskMulticlassProbsPosterior",
    "MulticlassClassificationGPModel",
    "MulticlassClassificationMixedGPModel",
    "build_mixed_multiclass_kernel",
    "MultiOutputMulticlassProbsPosterior",
    "MultiOutputMulticlassClassificationModel",
    "MultiOutputMulticlassModel",
    "MultiOutputMulticlassClassificationGPModel",
    "MultiTaskMulticlassClassificationGPModel",
    "MultiTaskMulticlassClassificationMixedGPModel",
    "DeepKernelMulticlassClassificationGPModel",
    "DeepKernelMulticlassClassificationMixedGPModel",
    "DeepMulticlassClassificationGPModel",
    "DeepMulticlassClassificationMixedGPModel",
    "SaasMulticlassClassificationGPModel",
    "SaasMulticlassClassificationMixedGPModel",
    "PCAMulticlassClassificationGPModel",
    "PCAMulticlassClassificationMixedGPModel",
    "REMBOMulticlassClassificationGPModel",
    "REMBOMulticlassClassificationMixedGPModel",
    "SparseOutlierSoftmaxLikelihood",
    "RobustRelevancePursuitMulticlassClassificationGPModel",
    "RobustRelevancePursuitMulticlassClassificationMixedGPModel",
    "HeteroscedasticMulticlassPosterior",
    "HeteroscedasticMulticlassClassificationGPModel",
    "HeteroscedasticMulticlassClassificationMixedGPModel",
]
