"""Pydantic schemas for bochan FastAPI serving."""

from __future__ import annotations

from .configs import (
    AcquisitionConfigSchema,
    CandidateRepairConfigSchema,
    DataContextSchema,
    FitConfigSchema,
    InputTransformConfigSchema,
    ModelConfigSchema,
    MultiObjectiveConfigSchema,
    MultiOutputConfigSchema,
    ObjectiveConfigSchema,
    OptimizeConfigSchema,
    OutcomeConstraintConfigSchema,
    OutputConfigSchema,
)
from .requests import (
    APIRequest,
    AutoCandidateRequest,
    CandidateRequest,
    CompareCandidatesRequest,
    FitModelRequest,
    LLMConfigSchema,
    LLMContextSchema,
    LLMPlanRequest,
    LoadModelRequest,
    PredictRequest,
    RefitModelRequest,
    SaveModelRequest,
    SuggestRequest,
    TabularBatchCandidateRequest,
    TellRequest,
    TensorOptionsSchema,
)
from .responses import (
    AcquisitionNamesResponse,
    CandidateResponse,
    CompareCandidatesResponse,
    HealthResponse,
    LoadModelResponse,
    ModelDeleteResponse,
    ModelFitResponse,
    ModelListResponse,
    PredictResponse,
    SavedModelsResponse,
    SaveModelResponse,
    TabularBatchCandidateResponse,
    TabularBatchCandidateResult,
)

__all__ = [
    "APIRequest",
    "AcquisitionConfigSchema",
    "AcquisitionNamesResponse",
    "AutoCandidateRequest",
    "CandidateRepairConfigSchema",
    "CandidateRequest",
    "CandidateResponse",
    "CompareCandidatesRequest",
    "CompareCandidatesResponse",
    "DataContextSchema",
    "FitConfigSchema",
    "FitModelRequest",
    "HealthResponse",
    "InputTransformConfigSchema",
    "LLMConfigSchema",
    "LLMContextSchema",
    "LLMPlanRequest",
    "LoadModelRequest",
    "LoadModelResponse",
    "ModelConfigSchema",
    "ModelDeleteResponse",
    "ModelFitResponse",
    "ModelListResponse",
    "MultiObjectiveConfigSchema",
    "MultiOutputConfigSchema",
    "ObjectiveConfigSchema",
    "OptimizeConfigSchema",
    "OutcomeConstraintConfigSchema",
    "OutputConfigSchema",
    "PredictRequest",
    "PredictResponse",
    "RefitModelRequest",
    "SaveModelRequest",
    "SaveModelResponse",
    "SavedModelsResponse",
    "SuggestRequest",
    "TabularBatchCandidateRequest",
    "TabularBatchCandidateResponse",
    "TabularBatchCandidateResult",
    "TellRequest",
    "TensorOptionsSchema",
]
