"""Constraint-space compatibility for classification multi-objective acquisitions.

BoTorch evaluates acquisition ``constraints`` on raw posterior samples. Binary
probability samples already have the public ``[..., q, m]`` layout, but ordinal
samples are latent values and multiclass samples include a final class axis
``[..., q, m, C]``. Constraints generated by ``OutcomeConstraintConfig`` refer to
public objective outputs and therefore must be evaluated after probability /
utility objectives. Explicit advanced callables retain raw-sample semantics.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import Any

from torch import Tensor
from botorch.utils.objective import compute_smoothed_feasibility_indicator

from bochan.acquisition.objective.outcome_constraints import (
    OutcomeConstraint,
    split_outcome_constraints,
    wrap_objective_space_constraints,
)


_APPLIED = False


def _feasibility_factor(
    *,
    raw_constraints: Sequence[OutcomeConstraint],
    objective_constraints: Sequence[OutcomeConstraint],
    raw_samples: Tensor,
    objective_values: Tensor,
    eta: float | Tensor,
    fat: bool,
) -> Tensor | None:
    """Return the product of raw- and objective-space feasibility indicators."""

    factor: Tensor | None = None
    if raw_constraints:
        factor = compute_smoothed_feasibility_indicator(
            constraints=list(raw_constraints),
            samples=raw_samples,
            eta=eta,
            fat=fat,
        )
    if objective_constraints:
        objective_factor = compute_smoothed_feasibility_indicator(
            constraints=list(objective_constraints),
            samples=objective_values,
            eta=eta,
            fat=fat,
        )
        factor = objective_factor if factor is None else factor * objective_factor
    return factor


def _patch_hypervolume_constraints(acquisition_cls: type) -> None:
    """Evaluate generated constraints after the acquisition objective."""

    if getattr(acquisition_cls, "_bochan_objective_constraint_patched", False):
        return

    original_init = acquisition_cls.__init__

    def compatible_init(self, *args: Any, **kwargs: Any) -> None:
        constraints = kwargs.get("constraints")
        if constraints is not None:
            kwargs["constraints"] = wrap_objective_space_constraints(
                constraints,
                objective_getter=lambda: getattr(self, "objective", None),
            )
        original_init(self, *args, **kwargs)

    acquisition_cls.__init__ = compatible_init
    acquisition_cls._bochan_original_init_before_objective_constraints = original_init
    acquisition_cls._bochan_objective_constraint_patched = True


def _install_nparego_constraint_state(
    acquisition: Any,
    constraints: Sequence[OutcomeConstraint] | None,
    *,
    eta: float | Tensor,
    fat: bool,
) -> None:
    raw_constraints, objective_constraints = split_outcome_constraints(constraints)
    acquisition.constraints = list(constraints or [])
    acquisition._bochan_raw_constraints = raw_constraints
    acquisition._bochan_objective_constraints = objective_constraints
    acquisition.eta = eta
    acquisition.fat = bool(fat)


def _patch_binary_nparego() -> None:
    from bochan.acquisition.binary.bayesian_optimization import multi_output as module

    cls = module.qMultiOutputBinaryNParEGO
    if getattr(cls, "_bochan_objective_constraint_patched", False):
        return
    original_init = cls.__init__

    def compatible_init(
        self,
        *args: Any,
        constraints: Sequence[OutcomeConstraint] | None = None,
        eta: float | Tensor = 1e-3,
        fat: bool = False,
        **kwargs: Any,
    ) -> None:
        original_init(self, *args, **kwargs)
        _install_nparego_constraint_state(
            self,
            constraints,
            eta=eta,
            fat=fat,
        )

    @module.t_batch_mode_transform()
    def compatible_forward(self, X: Tensor) -> Tensor:
        Xq = module.ensure_q_batch(X)
        posterior = module._get_binary_mc_posterior_for_probability_samples(
            self.model,
            Xq,
            samples_are_probs=self.samples_are_probs,
            prefer_latent=(not self.samples_are_probs)
            and self.apply_sigmoid_if_needed,
        )
        samples = self.get_posterior_samples(posterior)
        probability_values = module.to_probability(
            samples,
            apply_sigmoid_if_needed=(
                not self.samples_are_probs or self.apply_sigmoid_if_needed
            ),
            eps=self.eps,
            name="NParEGO posterior samples",
            model=self.model,
            values_are_probs=self.samples_are_probs,
        )
        objective_values = self.base_objective(probability_values, X=Xq)
        scalarized = self._scalarize(objective_values)
        improvement = (
            scalarized - self.best_value.to(scalarized)
        ).clamp_min(0.0)
        factor = _feasibility_factor(
            raw_constraints=self._bochan_raw_constraints,
            objective_constraints=self._bochan_objective_constraints,
            raw_samples=probability_values,
            objective_values=objective_values,
            eta=self.eta,
            fat=self.fat,
        )
        if factor is not None:
            improvement = improvement * factor
        return module._reduce_sample_and_q_to_tbatch(improvement, Xq)

    cls.__init__ = compatible_init
    cls.forward = compatible_forward
    cls._bochan_original_init_before_objective_constraints = original_init
    cls._bochan_objective_constraint_patched = True


def _patch_ordinal_nparego() -> None:
    from bochan.acquisition.ordinal.bayesian_optimization import multi_output as module

    cls = module.qMultiOutputOrdinalNParEGO
    if getattr(cls, "_bochan_objective_constraint_patched", False):
        return
    original_init = cls.__init__

    def compatible_init(
        self,
        *args: Any,
        constraints: Sequence[OutcomeConstraint] | None = None,
        eta: float | Tensor = 1e-3,
        fat: bool = False,
        **kwargs: Any,
    ) -> None:
        original_init(self, *args, **kwargs)
        _install_nparego_constraint_state(
            self,
            constraints,
            eta=eta,
            fat=fat,
        )

    @module.t_batch_mode_transform()
    def compatible_forward(self, X: Tensor) -> Tensor:
        Xq = module.ensure_q_batch(X)
        posterior = self.model.posterior(Xq)
        samples = self.get_posterior_samples(posterior)
        objective_values = self.base_objective(samples, X=Xq)
        scalarized = self._scalarize(objective_values)
        improvement = (
            scalarized - self.best_value.to(scalarized)
        ).clamp_min(0.0)
        factor = _feasibility_factor(
            raw_constraints=self._bochan_raw_constraints,
            objective_constraints=self._bochan_objective_constraints,
            raw_samples=samples,
            objective_values=objective_values,
            eta=self.eta,
            fat=self.fat,
        )
        if factor is not None:
            improvement = improvement * factor
        return module._reduce_sample_and_q_to_tbatch(improvement, Xq)

    cls.__init__ = compatible_init
    cls.forward = compatible_forward
    cls._bochan_original_init_before_objective_constraints = original_init
    cls._bochan_objective_constraint_patched = True


def _patch_multiclass_nparego() -> None:
    from bochan.acquisition.multiclass.bayesian_optimization import multi_output as module

    cls = module.qMultiOutputMulticlassNParEGO
    if getattr(cls, "_bochan_objective_constraint_patched", False):
        return
    original_init = cls.__init__

    def compatible_init(
        self,
        *args: Any,
        constraints: Sequence[OutcomeConstraint] | None = None,
        eta: float | Tensor = 1e-3,
        fat: bool = False,
        **kwargs: Any,
    ) -> None:
        original_init(self, *args, **kwargs)
        _install_nparego_constraint_state(
            self,
            constraints,
            eta=eta,
            fat=fat,
        )

    @module.t_batch_mode_transform()
    def compatible_forward(self, X: Tensor) -> Tensor:
        Xq = module.ensure_q_batch(X)
        posterior = self.model.posterior(Xq)
        samples = self.get_posterior_samples(posterior)
        objective_values = self.base_objective(samples, X=None)
        scalarized = self._scalarize(objective_values)
        improvement = (
            scalarized - self.best_value.to(scalarized)
        ).clamp_min(0.0)
        factor = _feasibility_factor(
            raw_constraints=self._bochan_raw_constraints,
            objective_constraints=self._bochan_objective_constraints,
            raw_samples=samples,
            objective_values=objective_values,
            eta=self.eta,
            fat=self.fat,
        )
        if factor is not None:
            improvement = improvement * factor
        return module._reduce_sample_and_q_to_tbatch(improvement, Xq)

    cls.__init__ = compatible_init
    cls.forward = compatible_forward
    cls._bochan_original_init_before_objective_constraints = original_init
    cls._bochan_objective_constraint_patched = True


def apply_classification_constraint_compat() -> None:
    """Install objective-space constraints across classification BO families."""

    global _APPLIED
    if _APPLIED:
        return

    from bochan.acquisition.binary.bayesian_optimization import (
        qMultiOutputBinaryExpectedHypervolumeImprovement,
        qMultiOutputBinaryNoisyExpectedHypervolumeImprovement,
    )
    from bochan.acquisition.multiclass.bayesian_optimization import (
        qMultiOutputMulticlassExpectedHypervolumeImprovement,
        qMultiOutputMulticlassNoisyExpectedHypervolumeImprovement,
    )
    from bochan.acquisition.ordinal.bayesian_optimization import (
        qMultiOutputOrdinalExpectedHypervolumeImprovement,
        qMultiOutputOrdinalNoisyExpectedHypervolumeImprovement,
    )

    for acquisition_cls in (
        qMultiOutputBinaryExpectedHypervolumeImprovement,
        qMultiOutputBinaryNoisyExpectedHypervolumeImprovement,
        qMultiOutputOrdinalExpectedHypervolumeImprovement,
        qMultiOutputOrdinalNoisyExpectedHypervolumeImprovement,
        qMultiOutputMulticlassExpectedHypervolumeImprovement,
        qMultiOutputMulticlassNoisyExpectedHypervolumeImprovement,
    ):
        _patch_hypervolume_constraints(acquisition_cls)

    _patch_binary_nparego()
    _patch_ordinal_nparego()
    _patch_multiclass_nparego()
    _APPLIED = True


__all__ = ["apply_classification_constraint_compat"]
