"""Multiclass acquisition functions."""

from .active_learning import (
    qHeteroMultiOutputMulticlassBALD,
    qHeteroMultiOutputMulticlassGreedyJointBALD,
    qHeteroMultiOutputMulticlassIntegratedPosteriorVarianceProxy,
    qHeteroMultiOutputMulticlassJointBALD,
    qHeteroMultiOutputMulticlassMarginUncertainty,
    qHeteroMultiOutputMulticlassPredictiveEntropy,
    qHeteroMultiOutputMulticlassProbabilityVariance,
    qHeteroMulticlassBALD,
    qHeteroMulticlassIntegratedPosteriorVarianceProxy,
    qHeteroMulticlassMarginUncertainty,
    qHeteroMulticlassPredictiveEntropy,
    qHeteroMulticlassProbabilityVariance,
    qMultiOutputMulticlassBALD,
    qMultiOutputMulticlassGreedyJointBALD,
    qMultiOutputMulticlassIntegratedPosteriorVarianceProxy,
    qMultiOutputMulticlassJointBALD,
    qMultiOutputMulticlassMarginUncertainty,
    qMultiOutputMulticlassPredictiveEntropy,
    qMultiOutputMulticlassProbabilityVariance,
    qMulticlassBALD,
    qMulticlassGreedyJointBALD,
    qMulticlassIntegratedPosteriorVarianceProxy,
    qMulticlassJointBALD,
    qMulticlassMarginUncertainty,
    qMulticlassPredictiveEntropy,
    qMulticlassProbabilityVariance,
)
from .bayesian_optimization import (
    qHeteroMulticlassExpectedHypervolumeImprovement,
    qHeteroMulticlassExpectedImprovement,
    qHeteroMulticlassNParEGO,
    qHeteroMulticlassNoisyExpectedHypervolumeImprovement,
    qHeteroMulticlassProbabilityOfFeasibility,
    qHeteroMulticlassProbabilityOfImprovement,
    qHeteroMulticlassUpperConfidenceBound,
    qMulticlassExpectedHypervolumeImprovement,
    qMulticlassExpectedImprovement,
    qMulticlassNParEGO,
    qMulticlassNoisyExpectedHypervolumeImprovement,
    qMulticlassProbabilityOfFeasibility,
    qMulticlassProbabilityOfImprovement,
    qMulticlassUpperConfidenceBound,
)
from .levelset_estimation import (
    NoiseCombineType,
    NoiseWeightMode,
    OutputReductionType,
    qHeteroMultiOutputMulticlassBoundaryVarianceAcquisition,
    qHeteroMultiOutputMulticlassClassEntropyAcquisition,
    qHeteroMultiOutputMulticlassICUAcquisition,
    qHeteroMultiOutputMulticlassJointLatentStraddleAcquisition,
    qHeteroMultiOutputMulticlassLatentStraddleAcquisition,
    qHeteroMultiOutputMulticlassLevelSetUncertainty,
    qHeteroMultiOutputMulticlassProbabilityOfExceedance,
    qHeteroMulticlassBoundaryVarianceAcquisition,
    qHeteroMulticlassClassEntropyAcquisition,
    qHeteroMulticlassICUAcquisition,
    qHeteroMulticlassJointLatentStraddleAcquisition,
    qHeteroMulticlassLatentStraddleAcquisition,
    qHeteroMulticlassLevelSetUncertainty,
    qHeteroMulticlassProbabilityOfExceedance,
    qMultiOutputMulticlassBoundaryVarianceAcquisition,
    qMultiOutputMulticlassClassEntropyAcquisition,
    qMultiOutputMulticlassICUAcquisition,
    qMultiOutputMulticlassJointLatentStraddleAcquisition,
    qMultiOutputMulticlassLatentStraddleAcquisition,
    qMultiOutputMulticlassLevelSetUncertainty,
    qMultiOutputMulticlassProbabilityOfExceedance,
    qMulticlassBoundaryVarianceAcquisition,
    qMulticlassClassEntropyAcquisition,
    qMulticlassICUAcquisition,
    qMulticlassJointLatentStraddleAcquisition,
    qMulticlassLatentStraddleAcquisition,
    qMulticlassLevelSetUncertainty,
    qMulticlassProbabilityOfExceedance,
)

__all__ = [
    name
    for name in globals()
    if name.startswith("q")
    or name in {"NoiseCombineType", "NoiseWeightMode", "OutputReductionType"}
]
