from .alignment_compat import apply_active_learning_alignment_compat
from .hetero_multi_output import (
    qHeteroMultiOutputMulticlassBALD,
    qHeteroMultiOutputMulticlassGreedyJointBALD,
    qHeteroMultiOutputMulticlassIntegratedPosteriorVarianceProxy,
    qHeteroMultiOutputMulticlassJointBALD,
    qHeteroMultiOutputMulticlassMarginUncertainty,
    qHeteroMultiOutputMulticlassPredictiveEntropy,
    qHeteroMultiOutputMulticlassProbabilityVariance,
)
from .hetero_single_output import (
    NoiseCombineType,
    NoiseQAggregateType,
    NoiseWeightMode,
    qHeteroMulticlassBALD,
    qHeteroMulticlassGreedyJointBALD,
    qHeteroMulticlassIntegratedPosteriorVarianceProxy,
    qHeteroMulticlassJointBALD,
    qHeteroMulticlassMarginUncertainty,
    qHeteroMulticlassPredictiveEntropy,
    qHeteroMulticlassProbabilityVariance,
)
from .multi_output import (
    OutputReductionType,
    qMultiOutputMulticlassBALD,
    qMultiOutputMulticlassGreedyJointBALD,
    qMultiOutputMulticlassIntegratedPosteriorVarianceProxy,
    qMultiOutputMulticlassJointBALD,
    qMultiOutputMulticlassMarginUncertainty,
    qMultiOutputMulticlassPredictiveEntropy,
    qMultiOutputMulticlassProbabilityVariance,
)
from .single_output import (
    qMulticlassBALD,
    qMulticlassGreedyJointBALD,
    qMulticlassIntegratedPosteriorVarianceProxy,
    qMulticlassJointBALD,
    qMulticlassMarginUncertainty,
    qMulticlassPredictiveEntropy,
    qMulticlassProbabilityVariance,
)

# DeepGP などで posterior sample / latent 軸が片側だけに残る場合の align 互換 patch。
apply_active_learning_alignment_compat()

__all__ = [
    "NoiseCombineType",
    "NoiseQAggregateType",
    "NoiseWeightMode",
    "OutputReductionType",
    "apply_active_learning_alignment_compat",
    "qMulticlassPredictiveEntropy",
    "qMulticlassProbabilityVariance",
    "qMulticlassMarginUncertainty",
    "qMulticlassBALD",
    "qMulticlassJointBALD",
    "qMulticlassGreedyJointBALD",
    "qMulticlassIntegratedPosteriorVarianceProxy",
    "qMultiOutputMulticlassPredictiveEntropy",
    "qMultiOutputMulticlassProbabilityVariance",
    "qMultiOutputMulticlassMarginUncertainty",
    "qMultiOutputMulticlassBALD",
    "qMultiOutputMulticlassJointBALD",
    "qMultiOutputMulticlassGreedyJointBALD",
    "qMultiOutputMulticlassIntegratedPosteriorVarianceProxy",
    "qHeteroMulticlassPredictiveEntropy",
    "qHeteroMulticlassProbabilityVariance",
    "qHeteroMulticlassMarginUncertainty",
    "qHeteroMulticlassBALD",
    "qHeteroMulticlassJointBALD",
    "qHeteroMulticlassGreedyJointBALD",
    "qHeteroMulticlassIntegratedPosteriorVarianceProxy",
    "qHeteroMultiOutputMulticlassPredictiveEntropy",
    "qHeteroMultiOutputMulticlassProbabilityVariance",
    "qHeteroMultiOutputMulticlassMarginUncertainty",
    "qHeteroMultiOutputMulticlassBALD",
    "qHeteroMultiOutputMulticlassJointBALD",
    "qHeteroMultiOutputMulticlassGreedyJointBALD",
    "qHeteroMultiOutputMulticlassIntegratedPosteriorVarianceProxy",
]
